#!/bin/bash
echo "before appending the file"
cat file.sh
echo "learning chapter 1" >> file.sh
echo "after appending the file"
cat "file.sh"
user1@ubuntu:~$ bash append_file.sh
before appending the file
echo hello world

after appending the file
echo hello world
learning chapter 1

