#!/bin/bash
user1@ubuntu:~$ nano while_examplee.sh
valid=true
count=1
while [ $valid ]
do 
echo $count
if [ $count -eq 5 ] ;
then 
break
fi
((count++))
done
user1@ubuntu:~$ bash while_examplee.sh
1
2
3
4
5

